### ISSUE TITLE
发电机在Y轴为负值时工作异常

### ISSUE THREAD

**Issue by StarCL6** [SlimefunGuguProject/DynaTech#21]
如题，1.18版本更新后，玩家可以前往更深的地底进行探索，但是当玩家尝试在Y轴为负的地方建立能源网络时，动力科技的发电机失效，部分日志如下(使用水力涡轮发电机进行实验)：

Error Generated: 2022-03-26-00-23

Java Environment:
  Operating System: Windows Server 2019
  Java Version: 17.0.2

Server Software: Spigot
  Build: 3406-Spigot-f4ff00f-7c3ac94 (MC: 1.18.1)
  Minecraft v1.18.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v4.9-release-2022.01
  Caused by: DynaTech vBuild 23 zh-CN(ybw0014) (git 3c525ad)

Installed Addons (9)
  + HotbarPets Build 2 zh-CN(ybw0014) (git 5afb147)
  + ExtraTools Build 1 zh-CN(baoad) (git 5b1065a)
  + DynaTech Build 23 zh-CN(ybw0014) (git 3c525ad)
  + ExtraGear Build 2 zh-CN(ybw0014) (git ff13031)
  + CMILib 1.1.2.3
  + WhatIsThis 4.6
  - Galactifun Build 3 zh-CN(baoad) (git 180ad5a)
  + TranscEndence Build 2 zh-CN(baoad) (git ae7bd81)
  + Residence 5.0.1.0

Block Info:
  World: world
  X: 70
  Y: -28
  Z: -308
  Material: PRISMARINE_WALL
  Block Data: org.bukkit.craftbukkit.v1_18_R1.block.impl.CraftCobbleWall
  State: org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState

Ticker-Info:
  Type: Indirect (Energy Network)

Slimefun Data:
  ID: WATER_TURBINE
  Inventory: false
  Data: {"id":"WATER_TURBINE"}

Stacktrace:

java.lang.IllegalArgumentException: y out of range (expected -64-320, got 4068)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453)
	at org.bukkit.craftbukkit.v1_18_R1.CraftChunk.validateChunkCoordinates(CraftChunk.java:372)
	at org.bukkit.craftbukkit.v1_18_R1.CraftChunk.getBlock(CraftChunk.java:114)
	at io.github.thebusybiscuit.slimefun4.libraries.dough.blocks.BlockPosition.getBlock(BlockPosition.java:146)
	at me.profelements.dynatech.items.electric.generators.HydroGenerator.fetchOutputForBlock(HydroGenerator.java:63)
	at me.profelements.dynatech.items.electric.generators.HydroGenerator.getGeneratedOutput(HydroGenerator.java:56)
	at io.github.thebusybiscuit.slimefun4.core.networks.energy.EnergyNet.tickAllGenerators(EnergyNet.java:220)
	at io.github.thebusybiscuit.slimefun4.core.networks.energy.EnergyNet.tick(EnergyNet.java:135)
	at io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator.tick(EnergyRegulator.java:86)
	at io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator.access$000(EnergyRegulator.java:34)
	at io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator$3.tick(EnergyRegulator.java:79)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

烦劳您可以利用空余时间进行修复，这个插件对我来说十分重要，万分感谢！

**Comment by ybw0014** [comment]
前置dough的问题，需要等待dough修复:
https://github.com/baked-libs/dough/issues/162

**Comment by ybw0014** [comment]
最新开发版已经修复，或者等6月的正式版。
只需要更新粘液本体即可。
