### ISSUE TITLE
NoSuchFieldError: SHORT_GRASS in GrowthChamberMK2

### ISSUE THREAD

**Issue by wling-art** [SlimefunGuguProject/DynaTech#66]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/DynaTech/issues)，且没有找到相同的问题

### 问题描述

在运行DynaTech插件时，出现了以下错误：
```
[00:58:43 ERROR]: Error occurred while enabling DynaTech vBuild 62 (git 973b6e8) (Is it up to date?)
java.lang.NoSuchFieldError: SHORT_GRASS
        at me.profelements.dynatech.items.electric.growthchambers.GrowthChamberMK2.registerDefaultRecipes(GrowthChamberMK2.java:62) ~[N[D][动力科技]DynaTech-Build 62 (git 973b6e8).jar:?]
        at me.profelements.dynatech.items.electric.growthchambers.GrowthChamberMK2.postRegister(GrowthChamberMK2.java:47) ~[N[D][动力科技]DynaTech-Build 62 (git 973b6e8).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:492) ~[[S][粘液科技]Slimefun-50f52a2-Beta.jar:?]
        at me.profelements.dynatech.setup.DynaTechItemsSetup.setup(DynaTechItemsSetup.java:316) ~[N[D][动力科技]DynaTech-Build 62 (git 973b6e8).jar:?]
        at me.profelements.dynatech.DynaTech.onEnable(DynaTech.java:63) ~[N[D][动力科技]DynaTech-Build 62 (git 973b6e8).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
进入服务器查看动力的列表只有 资源 工具 机器
![image](https://github.com/SlimefunGuguProject/DynaTech/assets/90316914/d5a9567a-efee-4b26-a1d3-15fa7835806f)

### 复现步骤

1. 启动服务器

### 预期行为

完整的显示列表

### 服务端软件

Purpur

### Minecraft 版本

1.20.2

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/DynaTech/assets/90316914/a29b6c8c-2e4e-43d1-a849-7dc16ce05625)

### 插件版本

Build 62 (git 973b6e8)

**Comment by ybw0014** [comment]
[71c05de](https://github.com/SlimefunGuguProject/DynaTech/commit/71c05de9e47b6b048de7913d9cd04351818e433c)
