### ISSUE TITLE
Error occurred while enabling DynaTech vBuild 82 (git 9958f77) (Is it up to date?)

### ISSUE THREAD

**Issue by Forizing** [SlimefunGuguProject/DynaTech#72]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/DynaTech/issues)，且没有找到相同的问题

### 问题描述

[22:49:39] [Server thread/ERROR]: Error occurred while enabling DynaTech vBuild 82 (git 9958f77) (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.Registry does not have member field 'org.bukkit.Registry EFFECT'
	at net.guizhanss.guizhanlib.minecraft.utils.compatibility.PotionEffectTypeX.getByKey(PotionEffectTypeX.java:41) ~[GuizhanLibPlugin-Build 43 (git 26e3dd7).jar:?]
	at net.guizhanss.guizhanlib.minecraft.utils.compatibility.PotionEffectTypeX.<clinit>(PotionEffectTypeX.java:28) ~[GuizhanLibPlugin-Build 43 (git 26e3dd7).jar:?]
	at me.profelements.dynatech.setup.DynaTechItemsSetup.setup(DynaTechItemsSetup.java:171) ~[DynaTech-Build 82 (git 9958f77).jar:?]
	at me.profelements.dynatech.DynaTech.onEnable(DynaTech.java:83) ~[DynaTech-Build 82 (git 9958f77).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:49:39] [Server thread/INFO]: [DynaTech] Disabling DynaTech vBuild 82 (git 9958f77)

### 复现步骤

在Paper 1.20.1版本下使用Linux x86_64, Java JDK 21产生:
[22:49:39] [Server thread/ERROR]: Error occurred while enabling DynaTech vBuild 82 (git 9958f77) (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.Registry does not have member field 'org.bukkit.Registry EFFECT'
	at net.guizhanss.guizhanlib.minecraft.utils.compatibility.PotionEffectTypeX.getByKey(PotionEffectTypeX.java:41) ~[GuizhanLibPlugin-Build 43 (git 26e3dd7).jar:?]
	at net.guizhanss.guizhanlib.minecraft.utils.compatibility.PotionEffectTypeX.<clinit>(PotionEffectTypeX.java:28) ~[GuizhanLibPlugin-Build 43 (git 26e3dd7).jar:?]
	at me.profelements.dynatech.setup.DynaTechItemsSetup.setup(DynaTechItemsSetup.java:171) ~[DynaTech-Build 82 (git 9958f77).jar:?]
	at me.profelements.dynatech.DynaTech.onEnable(DynaTech.java:83) ~[DynaTech-Build 82 (git 9958f77).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:49:39] [Server thread/INFO]: [DynaTech] Disabling DynaTech vBuild 82 (git 9958f77)

### 预期行为

不知道

### 服务端软件

Paper

### Minecraft 版本

1.20.1

### Slimefun版本

Paper git-Paper-196 (MC: 1.20.1)
Slimefun 2024.09-release
Metrics-组件 #29
Java 21

### 插件版本

build 82 (git 9958f77)

**Comment by ybw0014** [comment]
已在快照版中修复，等待 GuizhanLib 插件版的下一次更新

**Comment by ybw0014** [comment]
更新 GuizhanLibPlugin 应该修复了

**Comment by Forizing** [comment]
好的
